### ISSUE TITLE
UnboundLocalError: local variable 'retStr' referenced before assignment, on Windows11

### ISSUE THREAD

**Issue by bk111** [tquangsdh20/text2ipa#5]
Traceback (most recent call last):
  File "c:\Users\dengz\Downloads\new\5.py", line 412, in <module>
    text_en_cn_image.append('<span class="ipa">' + get_IPA(orinal_sentence_en_single, language) + '</span>')
  File "C:\Python310\lib\site-packages\text2ipa\__main__.py", line 107, in get_IPA
    retStr = __get_IPA_en(text, language, proxy)
  File "C:\Python310\lib\site-packages\text2ipa\__main__.py", line 99, in __get_IPA_en
    return retStr
UnboundLocalError: local variable 'retStr' referenced before assignment

**Comment by nidionis** [comment]
idem with the example given in the doc

**Comment by tquangsdh20** [comment]
This issue has been fixed with the new version 2.1.2. 
Update the doc. The languages consists "en" and "fr".
